# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [12]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'2.4.0'

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
z = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [11]:
z.nbytes,print("%d bytes" % z.nbytes)

80 bytes


(80, None)

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [15]:
 ```python
%run `python -c "import numpy; numpy.info(numpy.add)"`
```

SyntaxError: invalid syntax (1247639826.py, line 3)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [16]:
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [28]:
a = np.array([])
for i in range(10,50):
   a = np.insert(a, 0, values = i )
a[::-1]

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22.,
       23., 24., 25., 26., 27., 28., 29., 30., 31., 32., 33., 34., 35.,
       36., 37., 38., 39., 40., 41., 42., 43., 44., 45., 46., 47., 48.,
       49.])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [30]:
a

array([49., 48., 47., 46., 45., 44., 43., 42., 41., 40., 39., 38., 37.,
       36., 35., 34., 33., 32., 31., 30., 29., 28., 27., 26., 25., 24.,
       23., 22., 21., 20., 19., 18., 17., 16., 15., 14., 13., 12., 11.,
       10.])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [34]:
a = np.array([])
for i in range(0,9):
    a = np.append(a , i)
a.reshape(3,3)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [38]:
a = np.array([1,2,0,0,4,0])
for ind , val  in  enumerate(a) :
    if val != 0:
        print(ind)

0
1
4


#### 11. Create a 3x3 identity matrix (★☆☆)

In [39]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [41]:
a = np.array([])
for i in range(27):
    r = np.random.randint(0,100)
    a = np.append(a,r)
a.reshape(3,3,3)

array([[[72., 75., 64.],
        [32., 47., 72.],
        [ 1., 86.,  4.]],

       [[70., 17.,  8.],
        [90., 74., 21.],
        [29., 91., 18.]],

       [[98., 59., 64.],
        [ 9., 24., 33.],
        [14.,  3., 84.]]])

In [43]:
Z = np.random.randint(0 ,100 , (3,3,3))
Z

array([[[39, 10, 86],
        [ 7, 24, 55],
        [30, 84, 22]],

       [[91, 18, 68],
        [79, 17, 18],
        [38, 87, 22]],

       [[13, 69,  4],
        [10, 55, 25],
        [35,  2, 12]]], dtype=int32)

In [44]:
np.random.random((3,3,3))

array([[[0.20987604, 0.21213158, 0.83128462],
        [0.71244985, 0.464414  , 0.97161199],
        [0.46586198, 0.33173652, 0.22559599]],

       [[0.46366348, 0.60616754, 0.77573183],
        [0.67866434, 0.17120834, 0.51374937],
        [0.24201288, 0.95641875, 0.96871612]],

       [[0.85396485, 0.73909442, 0.40702125],
        [0.91392825, 0.35766625, 0.4379676 ],
        [0.22256301, 0.74256305, 0.34349384]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [47]:

np.random.random((10,10))

array([[0.12502429, 0.32733606, 0.36098187, 0.08417717, 0.08049949,
        0.25212124, 0.91196053, 0.75926377, 0.45819912, 0.12330615],
       [0.24425671, 0.56233911, 0.7045963 , 0.86546924, 0.33941972,
        0.43220352, 0.70669093, 0.47777119, 0.40274509, 0.60657482],
       [0.00901916, 0.90484293, 0.63903654, 0.96671951, 0.7342692 ,
        0.47434086, 0.02262892, 0.89555062, 0.06893813, 0.71361455],
       [0.61009289, 0.18622637, 0.86494482, 0.80497587, 0.85393066,
        0.30693925, 0.70064395, 0.65007894, 0.56748113, 0.87696143],
       [0.15889296, 0.68272211, 0.37761835, 0.50159868, 0.37324615,
        0.49498751, 0.54552118, 0.69888421, 0.42560212, 0.99222172],
       [0.41468084, 0.46113793, 0.74143664, 0.01424355, 0.80984072,
        0.57059709, 0.89981458, 0.04678169, 0.18553456, 0.61293158],
       [0.20965904, 0.88808897, 0.65961261, 0.45520667, 0.40377314,
        0.52058769, 0.80511331, 0.40833727, 0.22456613, 0.82485866],
       [0.57688151, 0.47837962, 0.3921309

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [49]:
z = np.random.randint(0 , 100 , (30))
z.mean()

np.float64(53.2)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [53]:
a = np.ones((5,5))
a[1:-1,1:-1] = 0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [115]:
a = np.ones((5,5))
a[[0,-1], :] = 0 
a[:, [0,-1]] = 0
a

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [116]:
a = np.pad(a , pad_width=1 , mode = "constant" , constant_values = 1)
a

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 1., 1., 1., 0., 1.],
       [1., 0., 1., 1., 1., 0., 1.],
       [1., 0., 1., 1., 1., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [74]:
a = [1, 2, 3, 4, 5]
np.pad(a, (2, 3), 'constant', constant_values=(4, 6))

array([4, 4, 1, 2, 3, 4, 5, 6, 6, 6])

In [75]:
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [76]:
0 * np.nan

nan

In [77]:
np.nan == np.nan

False

In [78]:
np.inf > np.nan

False

In [79]:
np.nan - np.nan

nan

In [80]:
np.nan in set([np.nan])

True

In [81]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [90]:
np.diag(1 + np.arange(5) , k = 0 ) , np.diag(1 + np.arange(4) , k = -1 ),np.diag(1 + np.arange(4) , k = 1)

(array([[1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 4, 0],
        [0, 0, 0, 0, 5]]),
 array([[0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0],
        [0, 0, 0, 4, 0]]),
 array([[0, 1, 0, 0, 0],
        [0, 0, 2, 0, 0],
        [0, 0, 0, 3, 0],
        [0, 0, 0, 0, 4],
        [0, 0, 0, 0, 0]]))

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [102]:
a = np.ones((8,8))
a[1::2] = 0 
a
# it says select from first column than till last 2 specifies the jump 

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [103]:
a = np.ones((8,8))
a[: , 1::2] = 0 
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [111]:
a = np.ones((8,8) , dtype = int)
a[1::2 , 0::2] = 0 
a[0::2 , 1::2] = 0 
a

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [110]:
Z = np.ones((8, 8), dtype=int)

# Set alternating cells to 0
Z[::2, ::2] = 0
Z[1::2, 1::2] = 0
Z

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [107]:


# The original array 'a' already has the desired pattern. 
# Assuming you wanted to *change* an existing list of zeros into this pattern:

# Example: Starting with a list of lists of zeros
a = [[0.] * 8 for _ in range(8)]

# Equivalent of a[1::2 , 0::2] = 1
# Loop through rows starting at index 1, step 2
for row_idx in range(1, 8, 2):
    # Loop through columns starting at index 0, step 2
    for col_idx in range(0, 8, 2):
        a[row_idx][col_idx] = 1.0

# Equivalent of a[0::2 , 1::2] = 1
# Loop through rows starting at index 0, step 2
for row_idx in range(0, 8, 2):
    # Loop through columns starting at index 1, step 2
    for col_idx in range(1, 8, 2):
        a[row_idx][col_idx] = 1.0

# Print the resulting list of lists
for row in a:
    print(row)



[0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
[1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0]
[0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
[1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0]
[0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
[1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0]
[0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0]
[1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [120]:
a = np.ones((6,7,8) , dtype=int)
print(np.unravel_index(99 , (6,7,8)))
np.unravel_index(99,(6,7,8) , "F")


(np.int64(1), np.int64(5), np.int64(3))


(np.int64(3), np.int64(2), np.int64(2))

In [127]:
a  = np.random.random((3,3,3))
print(np.unravel_index(22, (3,3,3)) , np.unravel_index(22 , (3,3,3), "F"))
a

(np.int64(2), np.int64(1), np.int64(1)) (np.int64(1), np.int64(1), np.int64(2))


array([[[0.23670519, 0.74162622, 0.74278735],
        [0.81803526, 0.22313279, 0.55299592],
        [0.16899005, 0.89262805, 0.48143707]],

       [[0.33927475, 0.7823628 , 0.91909844],
        [0.53722993, 0.05624764, 0.78769307],
        [0.8800568 , 0.64075641, 0.0522053 ]],

       [[0.16340749, 0.72752855, 0.00907125],
        [0.73861908, 0.93463271, 0.08343165],
        [0.35455011, 0.99863891, 0.07082516]]])

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [128]:
np.tile(np.array(([0,1],[1,0])),(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [145]:
# it will result array of two numbers whose sum is 6  
z = np.random.randint(6 ,200 ,  size = (5,5))
z


array([[136,  87,   6, 181, 115],
       [ 73,  10,  41,  17,  41],
       [155,  19, 194,  97, 173],
       [ 69,  54, 184, 129,  22],
       [104,  85,  19, 133,  72]], dtype=int32)

In [147]:
z = (z - np.mean (z)) / (np.std (z))
z

array([[ 0.80732285, -0.02795628, -1.40872383,  1.57441594,  0.44934608],
       [-0.26660746, -1.34053778, -0.81209588, -1.22121219, -0.81209588],
       [ 1.1312066 , -1.18711916,  1.7960206 ,  0.14250885,  1.43804383],
       [-0.33479351, -0.59049121,  1.62555547,  0.68799726, -1.13597962],
       [ 0.26183444, -0.06204931, -1.18711916,  0.75618331, -0.28365398]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [149]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [160]:
z = np.random.randint(1,6 ,  size = (5,3))
z1 = np.random.randint(1,6, size = (3,2))
z @ z1 , np.dot(z, z1)

(array([[16, 11],
        [19, 13],
        [29, 36],
        [28, 23],
        [31, 23]], dtype=int32),
 array([[16, 11],
        [19, 13],
        [29, 36],
        [28, 23],
        [31, 23]], dtype=int32))

In [165]:
# matmul is faster than dot product although they give same results 
Z = np.matmul(np.ones((5, 3)), np.ones((3, 2)))
print(Z)
Z = np.dot(np.ones((5, 3)), np.ones((3, 2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [172]:
n = np.random.randint(1,9,(1,8))
print(np.where((3 < n) & (n < 8), -n, n))
if ((n > 3) | (n < 8)).all():
    print("Every number is not between 3 and 8")

[[ 3 -7  8 -7 -5 -5 -7  8]]
Every number is not between 3 and 8


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [13]:
print(sum(range(5),-1))
j = 0 
for i in range(5):
    j += i 
print(j)

9
10


In [14]:
import numpy as np

print(np.sum(range(5),-1))

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [34]:
Z = np.random.randint(1,3,(1,4))
Z

array([[1, 1, 2, 2]], dtype=int32)

In [35]:
Z**Z

array([[1, 1, 4, 4]], dtype=int32)

In [36]:
2 << Z 

array([[4, 4, 8, 8]], dtype=int32)

In [37]:
Z << 2

array([[4, 4, 8, 8]], dtype=int32)

In [38]:
Z >> 2

array([[0, 0, 0, 0]], dtype=int32)

In [43]:
Z > - Z

array([[ True,  True,  True,  True]])

In [46]:
1j+Z, 1j*Z

(array([[1.+1.j, 1.+1.j, 2.+1.j, 2.+1.j]]),
 array([[0.+1.j, 0.+1.j, 0.+2.j, 0.+2.j]]))

In [49]:
Z/2

array([[0.5, 0.5, 1. , 1. ]])

In [50]:
Z/2/2

array([[0.25, 0.25, 0.5 , 0.5 ]])

In [59]:
Z<Z

array([[False, False, False, False]])

In [60]:
Z>Z

array([[False, False, False, False]])

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [61]:
np.array(0) / np.array(0)

C:\Users\HP\AppData\Local\Temp\ipykernel_28372\873513115.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


np.float64(nan)

In [62]:
np.array(0) // np.array(0)

C:\Users\HP\AppData\Local\Temp\ipykernel_28372\2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


np.int64(0)

In [63]:
np.array([np.nan]).astype(int).astype(float)

C:\Users\HP\AppData\Local\Temp\ipykernel_28372\699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [67]:
Z = np.random.uniform(-10,+10,10)
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))
print(np.copysign(np.ceil(np.abs(Z)), Z))

[-1. 10. -4.  8. -2.  7.  4. -9.  7. -5.]
[-1. 10. -4.  8. -2.  7.  4. -9.  7. -5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [70]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))
Z1 ,Z2

[0 1 3 5 7 9]


(array([7, 8, 7, 5, 4, 0, 9, 5, 3, 1], dtype=int32),
 array([1, 7, 5, 0, 2, 5, 3, 5, 0, 9], dtype=int32))

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [2]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

In [3]:
Z

array([inf])

In [4]:
# Back to sanity
_ = np.seterr(**defaults)

In [8]:
# it actually changes to new configuration and and stores old configuration in thier variable
_ , defaults

({'divide': 'ignore',
  'over': 'ignore',
  'under': 'ignore',
  'invalid': 'ignore'},
 {'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'})

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [9]:
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\HP\AppData\Local\Temp\ipykernel_20516\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [11]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
yesterday, today , tomorrow

(np.datetime64('2025-12-27'),
 np.datetime64('2025-12-28'),
 np.datetime64('2025-12-29'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [13]:
z = np.arange("2016-07" , "2016-08" , dtype="datetime64[D]")
z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)