In [1]:
import torch
import numpy as np

In [2]:
torch.__version__

'2.6.0+cu124'

In [3]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
type(x_data)

torch.Tensor

In [34]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(type(x_np))
type(x_np.numpy())

<class 'torch.Tensor'>


numpy.ndarray

In [7]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.6121, 0.1471],
        [0.5029, 0.1867]]) 



# but no change in x_data just retain the property of x_data

In [8]:
x_data

tensor([[1, 2],
        [3, 4]])

In [9]:
shape = (2,3,) # this is tuple used to define the shape 
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6726, 0.9639, 0.6888],
        [0.5635, 0.9387, 0.6343]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [10]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [11]:
tensor 

tensor([[0.5753, 0.5369, 0.3009, 0.5976],
        [0.4020, 0.2961, 0.3749, 0.8767],
        [0.7161, 0.0189, 0.4500, 0.6401]])

In [12]:
# by default tensors are created on cpu and if we want to wrok on 
# tensors with GPU we need to use .to function to move the tensor on
# accelator/GPU 
torch.accelerator.is_available()

True

In [13]:
torch.accelerator.current_accelerator()

device(type='cuda')

In [14]:
tensor = tensor.to(torch.accelerator.current_accelerator())
tensor 

tensor([[0.5753, 0.5369, 0.3009, 0.5976],
        [0.4020, 0.2961, 0.3749, 0.8767],
        [0.7161, 0.0189, 0.4500, 0.6401]], device='cuda:0')

In [15]:
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())
tensor 

tensor([[0.5753, 0.5369, 0.3009, 0.5976],
        [0.4020, 0.2961, 0.3749, 0.8767],
        [0.7161, 0.0189, 0.4500, 0.6401]], device='cuda:0')

In [16]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [17]:
# using .cat fucntion of torch module we can concatenate the tensors 
tensor = torch.randint(low=1, high=5, size=(2, 2), dtype=torch.int64)
tensor

tensor([[2, 2],
        [4, 4]])

In [18]:
t1 = torch.cat([tensor, tensor, tensor], dim=0) # dim = 0 will rowwise concatination 
print(t1)

tensor([[2, 2],
        [4, 4],
        [2, 2],
        [4, 4],
        [2, 2],
        [4, 4]])


In [19]:
t2 = torch.cat([tensor, tensor, tensor], dim=1)
t2

tensor([[2, 2, 2, 2, 2, 2],
        [4, 4, 4, 4, 4, 4]])

In [20]:
tensor 

tensor([[2, 2],
        [4, 4]])

In [21]:
y1 = tensor @ tensor.T 
y1 , tensor @ tensor 

(tensor([[ 8, 16],
         [16, 32]]),
 tensor([[12, 12],
         [24, 24]]))

In [22]:
tensor.matmul(tensor.T)

tensor([[ 8, 16],
        [16, 32]])

In [24]:
y2 = torch.ones_like(y1)
y2

tensor([[1, 1],
        [1, 1]])

In [25]:
type(y1)

torch.Tensor

In [26]:
print(y1)
torch.rand_like(y1, dtype=torch.float64)


tensor([[ 8, 16],
        [16, 32]])


tensor([[0.4728, 0.2833],
        [0.6640, 0.7565]], dtype=torch.float64)

In [27]:
   # ✅ correct
y1 = y1.to(torch.float64)
y1

tensor([[ 8., 16.],
        [16., 32.]], dtype=torch.float64)

In [28]:
tensor = torch.tensor([
    [1., 0., 1., 1.],
    [1., 0., 1., 1.],
    [1., 0., 1., 1.],
    [1., 0., 1., 1.]
])

z3 = torch.rand_like(tensor)
print(z3)


tensor([[0.1448, 0.1660, 0.4864, 0.9070],
        [0.5670, 0.4860, 0.0842, 0.5547],
        [0.1990, 0.7658, 0.8621, 0.0137],
        [0.7069, 0.0960, 0.3026, 0.3585]])


In [30]:
y1 = y1.to(torch.int32)  
y1

tensor([[ 8, 16],
        [16, 32]], dtype=torch.int32)

In [31]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [35]:
t.add_(1)
# if we use t.add(1) than inplace is not true and with underscore inplace is true
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [36]:
type(n)

numpy.ndarray

In [37]:
n = torch.from_numpy(n)
n.type , type(n)

(<function Tensor.type>, torch.Tensor)

In [38]:
n = np.ones(5)
t = torch.from_numpy(n)


In [39]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


In [40]:
# if we use numpy array in torch using .form_numpy or torch in numpy using 

In [47]:
A = torch.randn(1,3,4)
A

tensor([[[-1.1791,  0.8657,  0.5988, -0.1061],
         [ 0.2119, -0.5022, -0.0601, -0.9130],
         [-0.0679, -0.8647,  1.7433,  0.0810]]])

In [46]:
A.squeeze()

tensor([[ 0.3354, -2.0711, -1.1060, -0.5269],
        [-0.2536, -0.9741,  2.8520,  1.6149],
        [-0.0587,  0.9356,  0.4918, -0.9799]])

In [12]:
z = torch.zeros(1,83)
z

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
z.scatter(1,torch.tensor([1,2,34]).unsqueeze(0),1)

tensor([[0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [17]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])

out = torch.stack([a, b])
print(out)
print(out.shape)


tensor([[1, 2, 3],
        [4, 5, 6]])
torch.Size([2, 3])


In [21]:
l = [torch.tensor(x) for x in [1,2,3,4,5,6,7,8,9,0]]
torch.stack(l)


tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])