In [1]:
import numpy as np 

In [2]:
a = np.array([1,2,3])

In [3]:
a.ndim

1

In [4]:
a.shape

(3,)

In [5]:
b = a.copy()

In [6]:
id(a) , id(b)

(2686456750960, 2686456750480)

In [7]:
a.reshape(-1,1)

array([[1],
       [2],
       [3]])

In [8]:
b.reshape(1,-1)

array([[1, 2, 3]])

In [9]:
c = np.array([[1,1],[2,3]])


In [10]:
c

array([[1, 1],
       [2, 3]])

In [11]:
c.ndim

2

In [12]:
c = c.reshape(1,-1)

In [13]:
c = c[0]

In [14]:
T = c.T

In [15]:
 c = c.reshape(-1,1)

In [16]:
c.shape

(4, 1)

In [17]:
c.reshape(1,-1)[0].shape

(4,)

In [18]:
X = np.random.randn(4, 3)
b = np.random.randn(3)

print(X + b)
print(X * b)


[[-0.76604737  1.42759945 -0.57501202]
 [ 1.32245407  0.47593074 -1.50103026]
 [ 0.53149362  1.40966388 -0.24092772]
 [-1.31682214  0.12681425  0.54511062]]
[[-0.28086178 -0.40246473 -0.59499274]
 [ 0.28483778 -0.172947    0.43353803]
 [ 0.07059518 -0.39813914 -0.966061  ]
 [-0.43004676 -0.08874919 -1.83911574]]


In [19]:
X

array([[-1.03691122,  1.66877343,  0.53569047],
       [ 1.05159021,  0.71710472, -0.39032777],
       [ 0.26062976,  1.65083786,  0.86977476],
       [-1.587686  ,  0.36798823,  1.65581311]])

In [20]:
b

array([ 0.27086386, -0.24117398, -1.11070249])

In [21]:
X[0] + b

array([-0.76604737,  1.42759945, -0.57501202])

In [22]:
n = np.random.randn(2,2,2,2)

In [23]:
n.shape

(2, 2, 2, 2)

In [28]:
type(n)

numpy.ndarray

In [24]:
n.ndim

4

In [25]:
def non(n):
    assert n.ndim >=4 ,"nothing"
    return True 
non(n)

True

In [26]:
# dot product between two rows 
def dot1(a,b):
    s = 0 
    for i in range(len(a)):
        s += a[i]*b[i]
    return s

dot1([2,3],[3,4])

18

In [27]:
def dot(a, b):
    return np.sum(a * b)
dot(np.array([2,3]),np.array([3,4]))

np.int64(18)

In [32]:
def Mse(y , y_pred):
    assert type(y) == np.ndarray,  "not matches required datatype"

    loss = ((y - y_pred)**2)/y.shape[0]
    return loss 

Mse(np.random.randn(5) , np.random.randn(5))

array([0.29571607, 0.39829231, 0.19453882, 0.28194842, 0.12135581])

In [34]:
# This one is incorrect because / is more precedence than + 
# def Sigmoid(z):
#     return 1/1+ np.exp(-z)

def Sigmoid(z):
    return 1/(1+ np.exp(-z))
Sigmoid(10) 

np.float64(0.9999546021312976)

In [72]:
# ye mera wala h 
def Softmax(Z: np.array):
    soft = np.array([])
    for i in range(len(Z)):
        num = np.exp(Z[i])
        den = 0
        for j in np.concat((Z[0:i], Z[i+1:])):
            den += np.exp(j)
        den += num  

        soft = np.append(soft, num / den)

    return soft

In [73]:
z = np.array([1,2,3,4,5])
Softmax(z)

array([0.01165623, 0.03168492, 0.08612854, 0.23412166, 0.63640865])

In [74]:
# AI
def softmax_loop(Z: np.ndarray):
    soft = np.zeros(len(Z))
    den = np.sum(np.exp(Z))

    for i in range(len(Z)):
        soft[i] = np.exp(Z[i]) / den

    return soft
softmax_loop(z)

array([0.01165623, 0.03168492, 0.08612854, 0.23412166, 0.63640865])

In [75]:
# AI
def softmax(Z: np.ndarray):
    Z = Z - np.max(Z)          # numerical stability
    exp_Z = np.exp(Z)
    return exp_Z / np.sum(exp_Z)
softmax(z)

array([0.01165623, 0.03168492, 0.08612854, 0.23412166, 0.63640865])